[package]
name = "rust_rasterize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22.0"
sdl2 = "0.35.2"
tobj = "3.2.3"
